# Generated by Django 5.0.7 on 2024-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
    ]
