# Generated by Django 5.0.7 on 2024-11-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gymmember_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='registration_fee',
        ),
    ]
