# Generated by Django 5.0.7 on 2024-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gymmember_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='registration_fee',
            field=models.BooleanField(default=False),
        ),
    ]
