# Generated by Django 5.0.7 on 2024-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_gymmember_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overpayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
