# Generated by Django 5.0.7 on 2024-11-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_overpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='overpayment',
        ),
    ]
