# Generated by Django 5.0.7 on 2024-11-08 09:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_payment_overpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overpayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
