# Generated by Django 5.0.7 on 2024-11-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_overpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='overpayment',
        ),
    ]
