# Generated by Django 5.0.7 on 2024-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_payment_overpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
