# Generated by Django 5.0.7 on 2024-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gymmember_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='activation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
