# Generated by Django 5.0.7 on 2024-11-11 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_gymmember_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overpayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
