# Generated by Django 5.0.7 on 2024-11-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_membershipfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipFee',
        ),
        migrations.RemoveField(
            model_name='gymmember',
            name='last_fee_reset_date',
        ),
    ]
