# Generated by Django 5.1.3 on 2024-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_membershipfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
